module.exports = {
  errors: {
    en: {
      "ERR_LOGIN": "The email or password is incorrect",
      "ERR_NOT_EXIST": "Email is not registered",
      "ERR_STRONG_PASSWORD": "Password must have capital letters, numbers, and at least 6 characters",
      "ERR_PASSWORD_CONFIRMATION": "Password Confirmation is not match",
      "ERR_FORGOT": "Email or Code is incorrect, please try again",
      "EMAIL_INVALID": "That email address is already taken please choose another one",
      "PHONE_INVALID": "Phone number is already taken please choose another one",
      "ERR_USER_NOT_FOUND": "Email is not registered",
      "ERR_GLOBAL": "Something went wrong, please try again or contact our customer service",
      "ERR_RESEND_CODE": "You cannot resend the verification code, please contact our customer service",
      "ERR_CODE_VERIFICATION": "The verification code is incorrect",
      "ERR_LOCKED": "You have entered wrong password too many times. Please try again in",
      "ERR_PASSWORD": "Password is incorrect, please try again",
      "ERR_CANNOT_BE_EMPTY": "cannot be empty",
      "ERR_NOT_VALID": "This field is not valid",
      "ERR_CANNOT_EMPTY": "cannot be empty",
      "ERR_LENGTH_NOT_VALID": "length should be",
      "ERR_NUMERIC_ONLY": "numeric only",
      "ERR_EMAIL_NOT_VALID": "email is not valid",
      "ERR_FIELD_NOT_MATCH": "field is not match",
      "ERR_DATE_NOT_VALID": "date is not valid",
      "ERR_AGE_NOT_VALID": "age should be",
      "ERR_CANNOT_EQUAL": "cannot be equal with",
      "ERR_NUMERIC_VALUE": "number should be",
      "ERR_GT": " greather than ",
      "ERR_LT": " less than ",
      "ERR_EQ": " equal to ",
      "ERR_LTE": " less or equal than ",
      "ERR_GTE": " greather or equal than ",
      "ERR_SAVE_FORM": "Ops, we were unable to save the form, please check error message in input field and try again.",
      "ERR_TRANS_ACCOUNT_NOT_COMPLETE": "Your profile is incomplete, please complete it first to make the transaction.",
      "ERR_TRANS_ACCOUNT_NOT_VERIFY": "Your profile is in the verification process, you can resume the transaction once the profile has been successfully verified.",

      "CHECKOUT_ERROR_INSUFFICIENTBALANCE": "Sorry, your balance is insufficient",
      "CHECKOUT_ERROR_INSUFFICIENTUNIT": "Sorry, the product you have is insufficient",
      "CHECKOUT_ERROR_MIN": "Sorry, minimum purchase is not appropriate",
      "CHECKOUT_ERROR_MINBAL": "Sorry, at least the remaining unit product does not match",
      "CHECKOUT_ERROR_USERNOTYETDEPOSIT": "Sorry, you must make a deposit to continue the transaction (TBD)",
      "CHECKOUT_ERROR_ACTIVECARTNOTFOUND": "Sorry, your shopping cart is empty (TBD)",
      "CHECKOUT_ERROR_USERNOTYETVEIFIED": "Sorry, your account has not been verified by the system (TBD)",
      "CHECKOUT_ERROR_USERNOTCOMPLETE": "Sorry, you must complete the profile before making a transaction (TBD)",
      "CHECKOUT_ERROR_CODEWRONG": "Sorry, the verification code you entered is not correct",
      "SWITCHING_ERROR_CANNOT_EQUAL": "Sorry, you canot switch to same product (TBD)",
      "ERR_PASSWORD_EMPTY": "Please insert your password.",

      "ERR_FACE": "Your transaction is less than the minimum amount of purchase specified. Please change it first.",
      "ERR_FACE_SELL": "Your transaction is less than the minimum amount of sales specified. Please change it first.",
      "ERR_ONLY_REDEMPT": "The remaining units of your product are not sufficient for the minimum balance of the set",

      "ERR_UNKNOWN": "Ops, someting went wrong, please try again",

      "ERR_REMAINING_BALANCE": "You exceeded limit of your remaining balance, please contact us to remove the limitation"
    },
    idn: {
      "ERR_LOGIN": "Email atau password tidak benar",
      "ERR_NOT_EXIST": "Email tidak terdaftar",
      "ERR_STRONG_PASSWORD": "Katasandi harus memiliki huruf kapital, angka, dan minimal 6 karakter",
      "ERR_PASSWORD_CONFIRMATION": "Konfirmasi Katasandi tidak sesuai",
      "ERR_FORGOT": "Email atau Kode tidak benar, silahkan coba lagi",
      "EMAIL_INVALID": "Alamat email yang sudah terdaftar silahkan pilih yang lain",
      "PHONE_INVALID": "Nomor telpon genggam yang sudah terdaftar silahkan pilih yang lain",
      "ERR_USER_NOT_FOUND": "Email tidak terdaftar",
      "ERR_GLOBAL": "Terjadi kesalahan sistem, silahkan coba lagi atau hubungi pengaduan pelanggan kami",
      "ERR_RESEND_CODE": "Anda tidak bisa mengirim ulang kode verifikasi, silahkan hubungi pengaduan pelanggan kami",
      "ERR_CODE_VERIFICATION": "Kode verifikasi tidak benar",
      "ERR_LOCKED": "Akun anda telah dikunci untuk alasan keamanan, silahkan coba lagi dalam",
      "ERR_PASSWORD": "Katasandi tidak benar, silahkan coba lagi",
      "ERR_CANNOT_BE_EMPTY": "tidak boleh kosong",

      "ERR_NOT_VALID": "Isian ini tidak valid",
      "ERR_CANNOT_EMPTY": "tidak boleh kosong",
      "ERR_LENGTH_NOT_VALID": "panjang harus",
      "ERR_NUMERIC_ONLY": "hanya angka",
      "ERR_EMAIL_NOT_VALID": "email tidak valid",
      "ERR_FIELD_NOT_MATCH": "inputan tidak sesuai dengan",
      "ERR_DATE_NOT_VALID": "tanggal tidak valid",
      "ERR_AGE_NOT_VALID": "umur seharusnya",
      "ERR_CANNOT_EQUAL": "tidak boleh sama dengan",
      "ERR_NUMERIC_VALUE": "angka harus",
      "ERR_GT": " lebih besar dari ",
      "ERR_LT": " lebih kurang dari ",
      "ERR_EQ": " sama dengan ",
      "ERR_LTE": " kurang atau sama dengan ",
      "ERR_GTE": " lebih atau sama dengan ",
      "ERR_SAVE_FORM": "Ops, kami tidak dapat menyimpan formulir ini, periksa pesan kesalahan pada inputan dan coba lagi.",
      "ERR_TRANS_ACCOUNT_NOT_COMPLETE": "Profil Anda belum lengkap, silahkan lengkapi terlebih dahulu untuk dapat melakukan transaksi.",
      "ERR_TRANS_ACCOUNT_NOT_VERIFY": "Profil Anda sedang dalam proses verifikasi, Anda dapat melanjutkan transaksi setelah profil berhasil terverifikasi.",

      "CHECKOUT_ERROR_INSUFFICIENTBALANCE": "Maaf, saldo Anda tidak mencukupi",
      "CHECKOUT_ERROR_INSUFFICIENTUNIT": "Maaf, product yang anda punya tidak mencukupi",
      "CHECKOUT_ERROR_MIN": "Maaf, minimal pembelian tidak sesuai",
      "CHECKOUT_ERROR_MINBAL": "Maaf, minimal sisa unit product tidak sesuai",
      "CHECKOUT_ERROR_USERNOTYETDEPOSIT": "Maaf, Anda harus melakukan deposit untuk melanjutkan transaksi (TBD)",
      "CHECKOUT_ERROR_ACTIVECARTNOTFOUND": "Maaf, kantong belanja anda kosong (TBD)",
      "CHECKOUT_ERROR_USERNOTYETVEIFIED": "Maaf, akun Anda belum di verify oleh sistem (TBD)",
      "CHECKOUT_ERROR_USERNOTCOMPLETE": "Maaf, anda harus melengkapi profil sebelum melakukan transaksi (TBD)",
      "CHECKOUT_ERROR_CODEWRONG": "Maaf, kode verifikasi yang Anda masukkan tidak benar",
      "SWITCHING_ERROR_CANNOT_EQUAL": "Maaf, Switch tidak dapat dilakukan terhadap produk yang sama",
      "ERR_PASSWORD_EMPTY": "Masukkan kata sandi Anda.",

      "ERR_FACE": "Transaksi Anda kurang dari jumlah minimum pembelian yang ditetapkan. Silakan ubah terlebih dahulu.",
      "ERR_FACE_SELL": "Transaksi Anda kurang dari jumlah minimum penjualan yang ditetapkan. Silakan ubah terlebih dahulu.",
      "ERR_ONLY_REDEMPT": "Sisa unit product Anda tidak mencukupi batas minimum saldo yang ditetapkan",

      "ERR_UNKNOWN": "Ops, terjadi kesalahan, silahkan coba lagi.",

      "ERR_REMAINING_BALANCE": "Sisa Unit product yang Anda miliki kurang dari jumlah minimum saldo yang ditetapkan. Silakan ubah terlebih dahulu."
    }
  },
  label: {
    en: {
      "GREETING_MORNING": "Good Morning!",
      "GREETING_AFTERNOON": "Good Afternoon!",
      "GREETING_EVENING": "Good Evening!",
      "GREETING_WELCOME": "Welcome Back",
      "SUBMIT": "Submit",
      "ENTER_YOUR_DETAIL": "Enter your detail below here",
      "FORGOT_PASSWORD": "Forgot your password?",
      "DONT_HAVE_ACCOUNT": "Don't have an account yet?",
      "SIGN_UP_NOW": "Register now",
      "CLICK_HERE": "Click here",
      "ALREADY_HAVE_AN_ACCOUNT": "Already have an account?",
      "RESET_INSTRUCTION": "Please enter your email address below, we will send you an email with instructions on how to reset your password",
      "PASSWORD_CONFIRMATION": "Password Confirmation",
      "NEW_PASSWORD": "New Password",
      "CODE": "Code",
      "PASSWORD": "Password",
      "CHANGE_PASSWORD": "Change your password",
      "CHANGE_PASSWORD_INSTRUCTION": "We have sent a verification code to change the account password to your email, please use the code in the field below.",
      "BACK_TO_LOGIN": "Back to login page?",
      "RESET_SUCCESS": "Congratulation, your password successfully changed.",
      "REGISTER_INSTRUCTION": "Fill in the form below to get instant access",
      "PHONE_NUMBER": "Phone Number",
      "FULLNAME": "Fullname",
      "ACTIVATE_YOUR_ACCOUNT": "Activate Your Account",
      "ACTIVATE_YOUR_ACCOUNT_INSTRUCTION": "We have sent verification code to activate your account to ",
      "VERIFICATION_CODE": "Verification Code",
      "DIDNT_RECEIVE_CODE": "Did not receive verification code?",
      "RESEND": "Resend code",
      "SENDING": "Sending code...",
      "MINUTES": "minutes",
      "TOTAL_INVESTMENT": "Total Investment",
      "PENDING_TRANSACTION": "Pending Transaction",
      "SESSION_EXPIRED": "Your session has expired, please login again",
      "NOT_YOUR_ACCOUNT": "Not your account?",
      "HOLIDAY": "Please note that today is a trading holiday, all transactions will be processed after the trading holiday is over",
      "MENU_DASHBOARD": "Dashboard",
      "MENU_PORTFOLIO": "My Portfolio",
      "MENU_TRANSACTION": "Transactions",
      "MENU_CHANGE_PASSWORD": "Change Password",
      "MENU_LOGOUT": "Logout",
      "MENU_PROFILE": "Profile",
      "PROFILE_NOT_COMPLETE": "Complete your profile to enjoy the convenience of mutual fund transactions",
      "PROFILE_NOT_VERIFIED": "One more step to enjoy the convenience of mutual fund transactions, your profile is in the verification process.",
      "MENU_PROFILE_SUBHEAD": "Please fill in the Account Opening Form Mutual Fund follows the full. Make sure the charging of your data in accordance with the compliance data attached",
      "PERSONAL_INFORMATION_TITLE": "Personal Information",
      "PERSONAL_INFORMATION_DESCRIPTION": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet.",
      "SORT_BY_NAME": "Sort by name",
      "SORT_BY_PERFORMANCE": "Sort by performance",
      "SORT_BY_NAV": "Sort by last NAV",
      "SORT_BY_TYPE": "Sort by type",

      "FIRST_NAME_LABEL": "First name",
      "MIDDLE_NAME_LABEL": "Middle name",
      "LAST_NAME_LABEL": "Last name",
      "IDENTITY_LABEL": "Identity",
      "IDENTITY_NUMBER_LABEL": "Identity number",
      "IDENTITY_EXPIRED_LABEL": "Identity expired at",
      "LIFETIME_LABEL": "Lifetime identity",
      "NPWP_INPUT_LABEL": "NPWP number",

      "NATIONALITY_LABEL": "Nationality",
      "BIRTH_PLACE_LABEL": "Birthplace",
      "BIRTH_DATE_LABEL": "Birthdate",
      "BIRTH_COUNTRY_LABEL": "Country of birth",
      "GENDER_LABEL": "Gender",
      "MARITAL_STATUS_LABEL": "Maritas status",
      "SPOUSE_NAME_LABEL": "Spouse name",
      "SPOUSE_BIRTH_PLACE_LABEL": "Spouse birthplace",
      "SPOUSE_BIRTH_DATE_LABEL": "Spouse birthdate",
      "SPOUSE_MOBILE_PHONE_LABEL": "Spouse mobile phone number",
      "MOTHER_MAIDEN_NAME_LABEL": "Mother maiden name",
      "EDUCATION_LABEL": "Education",
      "RELIGION_LABEL": "Religion",
      "CORRESPONDENCE_ADDRESS_LABEL": "Correspondence address",
      "CORRESPONDENCE_CITY_LABEL": "Correspondence city",
      "CORRESPONDENCE_CITY_OTHER_LABEL": "Other correspondence city",
      "CORRESPONDENCE_POSTAL_CODE_LABEL": "Correspondence zipcode",
      "CORRESPONDENCE_COUNTRY_LABEL": "Correspondence country",
      "SAME_AS_CORRESPONDENCE_LABEL": "Domicile address same as correspondece address",
      "DOMICILE_ADDRESS_LABEL": "Domicile address",
      "DOMICILE_CITY_LABEL": "Domicile city",
      "DOMICILE_CITY_OTHER_LABEL": "Other domicile city",
      "DOMICILE_POSTAL_CODE_LABEL": "Domicile zipcode",
      "DOMICILE_COUNTRY_LABEL": "Domicile country",
      "EMAIL_LABEL": "Email address",
      "HANDPHONE_LABEL": "Mobile phone number",
      "PHONE_LABEL": "Phone number",
      "FAX_LABEL": "Faximile address",
      "ASSET_OWNERSHIP_LABEL": "Asset ownership",
      "ASSET_OWNERSHIP_OTHER_LABEL": "Asset ownership other",
      "SID_LABEL": "SID",
      "STATEMENT_LABEL": "Prefered statement",
      "KTP_LABEL": "Upload Identity (image or PDF)",
      "NPWP_LABEL": "Upload NPWP (image or PDF)",
      "DOESNT_HAVE_NPWP_LABEL": "Does not have NPWP",

      "JOB_INFORMATION_TITLE": "Job Information",
      "JOB_INFORMATION_DESCRIPTION": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet.",
      "OCCUPATION_LABEL": "Occupation",
      "SPOUSE_OCCUPATION_LABEL": "Spouse occupation",
      "PARENT_OCCUPATION_LABEL": "Parent occupation",
      "SPOUSE_NATURE_OF_BUSSINES_LABEL": "Spouse nature of bussines",
      "PARENT_NATURE_OF_BUSSINES_LABEL": "Parent nature of bussines",
      "SPOUSE_NATURE_OF_BUSSINES_OTHER_LABEL": "Spouse other nature of bussines",
      "PARENT_NATURE_OF_BUSSINES_OTHER_LABEL": "Parent other nature of bussines",
      "SPOUSE_ID_CARD_LABEL": "Spouse ID Card number",
      "PARENT_ID_CARD_LABEL": "Parent ID Card number",
      "SPOUSE_NATIONALITY_LABEL": "Spouse nationality",
      "PARENT_NATIONALITY_LABEL": "Parent nationality",
      "OCCUPATION_OTHER_LABEL": "Other occupation",
      "OCCUPATION_NATURE_OF_BUSSINES_LABEL": "Occupation nature of bussines",
      "OCCUPATION_NATURE_OF_BUSSINES_OTHER_LABEL": "Other occupation nature of bussines",
      "INCOME_LABEL": "Income",
      "SPOUSE_INCOME_LABEL": "Spouse income",
      "PARENT_INCOME_LABEL": "Parent income",
      "SOURCE_OF_INCOME_LABEL": "Source of income",
      "SOURCE_OF_INCOME_OTHER_LABEL": "Other source of income",

      "BANK_INFORMATION_TITLE": "Bank Information",
      "BANK_INFORMATION_DESCRIPTION": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet.",
      "BANK_NAME_LABEL": "Bank name",
      "BANK_BRANCH_NAME_LABEL": "Bank branch name",
      "BANK_ACCOUNT_NUMBER_LABEL": "Bank account number",
      "BANK_ACCOUNT_NAME_LABEL": "Bank account name",
      "BANK_ADDRESS_LABEL": "Bank address",
      "CURRENCY_LABEL": "Currency",

      "INVESTMENT_PURPOSE_TITLE": "Investment Purpose",
      "INVESTMENT_PURPOSE_DESCRIPTION": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet.",
      "INVESTMENT_OBJECTIVE_LABEL": "Investment Objective",
      "INVESTMENT_OBJECTIVE_OTHER_LABEL": "Other Investment Objective",

      "RISK_PROFILE_TITLE": "Risk Profile",
      "RISK_PROFILE_DESCRIPTION": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet.",
      "RISK_1_LABEL": "Select horizon / term of your investment",
      "RISK_2_LABEL": "How old are you today",
      "RISK_3_LABEL": "Where an investment results you want",
      "RISK_4_LABEL": "The level of risk could be borne in investments",
      "RISK_5_LABEL": "How large mutual fund investment allocation of total assets",
      "RISK_6_LABEL": "The purpose of the use of your investment in mutual funds",
      "RISK_7_LABEL": "The extent to which your knowledge about mutual funds",
      "RISK_8_LABEL": "What do you think about the downside risk (loss) in value of your investment",
      "YOUR_RISK_PROFILE_LABEL": "Your Risk Profile",

      "CUSTOMER_STATEMENT_TITLE": "Customer Statement",
      "CUSTOMER_STATEMENT_DESCRIPTION": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet.",
      "TNC_CUST_STATMNT": "<div class=\"tnc tnc-profile\"><ol><li>That all information above is correct, complete, accurate, honest, clear and are not misleading. I will declare to [PTapp] if any changes regarding the information above.</li><li>I acknowledge that I have received and considered the latest Prospectus relating to the Funds and that this application is based thereon.</li><li>I acknowledge that I have read, understood and accepted the Terms & Conditions printed (as may hereafter be amended, modified and supplemented from time to time in accordance with Indonesia law) and be bound by them.</li><li>I confirm that all the information made by me in this form shall remain valid and I also undertake to immediately notify [PTapp] on any changes to this information in writing.</li><li>I understand that all data stated in this KYC form can be used to update customer’s data. I observe to prevailing laws and regulation including but not limited to Law Number 8 year 2010 regarding Anti Money Laundering, Law Number 9 year 2013 regarding prevention and eradication of anti-terrorism financing and OJK Rule Number 22 year 2014 regarding Know Your Customer principles by Financial Services Providers in Capital Market.</li><li>[PTapp] may record oral communications that we provide including when face to face meeting or by telephone conversation or other means of communication, including through short message service (SMS), Blackberry messenger (BBM) and other electronic media. The records shall be used as evidendence of the implementation of KYC process, transaction, and other matters related to the ownership of [app] Mutual Fund, including any dispute that may arise between [PTapp] and I in the future.</li></ol></div>",
      "TERMS_COND_LABEL": "I agree with the statement about the Customer Account Opening [app]",

      "REVIEW_TITLE": "Review Your Profile",
      "REVIEW_DESCRIPTION": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet.",

      "SUCCESS_FORM_SUBMITED": "Your profile is successfully submitted, we will review your data",

      "PRODUCT_DETAIL_LABEL": "Product Details",
      "PRODUCT_PERFORMANCE_LABEL": "Product Performance Information",
      "PRODUCT_NEWS_AND_PROMO_LABEL": "News and Promos",

      "FUND_NAME_LABEL": "Product Name",
      "TYPE_LABEL": "Type",
      "NAV_AS_OF_LABEL": "NAV as of",
      "BALANCE_LABEL": "Balance",

      "BUY_LABEL": "BUY",
      "SELL_LABEL": "SELL",
      "SWITCH_LABEL": "SWITCH",

      "SEND_PAYMENT_LABEL": "Your transaction is being processed. Please make the payment <strong>before 13:00</strong> today to the following account:",
      "SEND_PAYMENT2_LABEL": "<strong>If you do not make the payment within a period of 3 days, then your transaction will be deleted from the system.</strong>",
      "SEND_PAYMENT3_LABEL": "<strong>You will receive the fund maximum of 7 business days after this transaction.</strong>",
      "SEND_PAYMENT4_LABEL": "<strong>Once verified, your product switcing will be processed immediately.</strong>",

      "RISK_NOT_MATCH_LABEL": "Your risk profile not match with this product",
      "ARE_YOU_SURE_LABEL": "You are about to update some information on your profile",
      "NO_UNIT_LABEL": "You don’t have unit for this Fund",

      "MINIMUM_LABEL": "Minimum",
      "AMOUNT_LABEL": "Amount",
      "CODE_LABEL": "Verification Code",
      "SEND_LABEL": "Send",

      "CODE_SUCCESSFULLY_SENT_LABEL": "Verification code successfully sent, please check your email / phone",
      "TOOMUCH_CODE_REQUEST": "Sorry, we not allow to re-send your security code more than 3 times. Please contact our support",


      "AGREEMENT_TRANSACTION": "I agree to perform transaction with [app] and understand the ",
      "TAC": "Terms and Conditions",
      "TRANSACTION_SUCCESS_LABEL": "Your transaction has been successfully processed",

      "YOU_HAVE_LABEL": "You have",
      "MIN_SELL_LABEL": "Minimum amount / unit for sell",
      "MIN_BALANCE_LABEL": "Minimum balance after transaction",
      "YOUR_REMAINING_BALANCE_LABEL": "Your remaining balance",

      "SELECT_BANK_LABEL": "Select your bank",
      "TERMS_CONDITION_LABEL": "Terms and Conditions",
      "SELECT_PRODUCT_SWITCH_LABEL": "Select your product target",

      "AVAILABLE_BALANCE_LABEL": "Available Balance",
      "AVAILABLE_UNIT_LABEL": "Available Unit",

      "NOT_RECOMENDED_LABEL": "[PTapp] (including its subsidiaries, associates and affiliates) ([app]) does not provide any offers, suggestions or recommendations for investing in the Funds I / In this case, I / we acted alone in analyzing and selecting the Fund and the investment decision was made not according to suggestions or recommendations of [app]. ",

      "LAST_NAV_LABEL": "Last NAV",
      "MY_PORTOFOLIO_LABEL": "Your Portfolio",
      "OTHER_PRODUCT_LABEL": "Other Product(s)",

      "TRANSACTION_LIST_LABEL": "Transaction List",
      "FIRST_LABEL": "First",
      "NEXT_LABEL": "Next",
      "PREVIOUS_LABEL": "Previous",
      "LAST_LABEL": "Last",

      "PENDING_LABEL": "Pending",
      "WAIT_FOR_VERIFICATION_LABEL": "Wait for verification",
      "COMPLETE_LABEL": "Complete",
      "EXPIRED_LABEL": "Expired",
      "TOTAL_BUY_LABEL": "Total buy",
      "TOTAL_SELL_LABEL": "Total sell",
      "TRANSACTION_DATE_LABEL": "Transaction date",
      "FEE_LABEL": "Fee",

      "PDF_DOWNLOAD_LABEL": "Download Profile as PDF",
      "EDIT_PROFILE_LABEL": "Edit profile",

      "THERE_IS_NO_DATA_LABEL": "There is no data to display",

      "PENDING_TRANSACTION_NOTIFICATION_LABEL": "You have multiple transactions that require confirmation, Please confirm your transaction for us to process immediately.",

      "TRANSACTION_DETAIL": "Transaction detail",
      "TRANSACTION_TYPE_LABEL": "Transaction type",

      "CONFIRMATION_DATA_LABEL": "Payment confirmation data",
      "BANK_FROM_LABEL": "Send money from",
      "BANK_DESTINATION_LABEL": "Send money to",
      "PAYMENT_PROOF_LABEL": "Payment receipt",
      "PAYMENT_DATE_LABEL": "Payment date",

      "CONFIRM_TRANSACTION_LABEL": "Payment Confirmation",

      "REPEAT_LABEL": "Redo",
      "CONTINUE_LABEL": "Continue",
      "CLOSE_LABEL": "Close",
      "ATTENTION_LABEL": "Attention",
      "CONFIRM_LESS_THAN_LABEL": "Your transaction is less than the amount you have entered. Please contact Client Service or redo your transaction.",
      "CONFIRM_MORE_THAN_LABEL": "Your transaction is more than the amount you've entered. Do you want to continue or redo the transaction?",
      "CONFIRM_SUCCESS_LABEL": "Once verified, the purchase of your product will be processed immediately.",
      "CONFIRM_SUCCESS_WITH_WARNING": "Your confirmation is past 1 PM After verification, your purchase of your product will be processed on the next day.",

      "OLD_PASSWORD_LABEL": "Old password",
      "NEW_PASSWORD_LABEL": "New password",
      "NEW_PASSWORD_CONFIRMATION_LABEL": "Confirm new password",

      "CHANGE_PASSWORD_SUCCESS_LABEL": "Your password was changed successfully",
      "CHANGE_PASSWORD_FAILED_LABEL": "Your old password is incorrect, please try again",

      "PLEASE_SIGN_HERE_LABEL": "Please sign here *",




      "GREETING_WELCOME": "Sign in",
      "GREETING_MORNING": "",
      "GREETING_AFTERNOON": "",
      "GREETING_EVENING": "",
      "ENTER_YOUR_DETAIL": "to continue <strong>PayOr</strong>",
      "YOUR_EMAIL_LABEL": "Your Email",
      "YOUR_PASSWORD_LABEL": "Your Password",
      "OUR_PRODUCT_LABEL": "Our Product",
      "GOOD_DAY_LABEL": "Good day",

      "CONSERVATIVE_LABEL": "Conservative",
      "AGGRESSIVE_LABEL": "Aggressive",
      "BALANCE_LABEL": "Balance",
      "SIGNIN_LABEL": "Signin",
      "REGISTER_LABEL": "Register"
    },
    idn: {
      "GREETING_MORNING": "Selamat Pagi!",
      "GREETING_AFTERNOON": "Selamat Siang!",
      "GREETING_EVENING": "Selamat Malam!",
      "GREETING_WELCOME": "Selamat Datang Kembali",
      "SUBMIT": "Kirim",
      "ENTER_YOUR_DETAIL": "Masukkan detail akun Anda di bawah ini",
      "FORGOT_PASSWORD": "Anda lupa password?",
      "DONT_HAVE_ACCOUNT": "Anda belum memiliki akun?",
      "SIGN_UP_NOW": "Daftar sekarang",
      "CLICK_HERE": "Klik disini",
      "ALREADY_HAVE_AN_ACCOUNT": "Anda sudah memiliki akun?",
      "RESET_INSTRUCTION": "Silakan masukkan alamat email Anda di bawah ini, kami akan mengirimkan email dengan instruksi tentang bagaimana untuk mereset password Anda",
      "PASSWORD_CONFIRMATION": "Konfirmasi Katasandi",
      "NEW_PASSWORD": "Katasandi baru",
      "CODE": "Kode",
      "PASSWORD": "Katasandi",
      "CHANGE_PASSWORD": "Ubah katasandi Anda",
      "CHANGE_PASSWORD_INSTRUCTION": "Kami telah mengirimkan kode verifikasi untuk mengubah password akun ke email Anda, silahkan gunakan kode tersebut pada isian dibawah ini.",
      "BACK_TO_LOGIN": "Kembali ke halaman login?",
      "RESET_SUCCESS": "Selamat, katasandi Anda telah berhasil diubah.",
      "REGISTER_INSTRUCTION": "Isi formulir dibawah ini dan nikmati kemudahan akses",
      "PHONE_NUMBER": "Nomor Telepon Genggam",
      "FULLNAME": "Nama Lengkap",
      "ACTIVATE_YOUR_ACCOUNT": "Aktifkan Akun Anda",
      "ACTIVATE_YOUR_ACCOUNT_INSTRUCTION": "Kami telah mengirimkan kode verifikasi untuk mengaktifkan akun anda ke ",
      "VERIFICATION_CODE": "Kode Verifikasi",
      "DIDNT_RECEIVE_CODE": "Belum menerima kode verifikasi?",
      "RESEND": "Kirim ulang",
      "SENDING": "Mengirim...",
      "MINUTES": "menit",
      "TOTAL_INVESTMENT": "Total Investasi",
      "PENDING_TRANSACTION": "Transaksi Pending",
      "SESSION_EXPIRED": "Sesi Anda telah berakhir, silahkan login ulang untuk melanjutkan",
      "NOT_YOUR_ACCOUNT": "Bukan akun Anda?",
      "HOLIDAY": "Perlu diketahui bahwa hari ini adalah hari libur perdagangan, semua transaksi akan diproses setelah libur perdagangan selesai",
      "MENU_DASHBOARD": "Dashboard",
      "MENU_PORTFOLIO": "Portofolio Saya",
      "MENU_TRANSACTION": "Transaksi",
      "MENU_CHANGE_PASSWORD": "Ganti Katasandi",
      "MENU_LOGOUT": "Keluar",
      "MENU_PROFILE": "Profil Saya",
      "PROFILE_NOT_COMPLETE": "Lengkapi profil Anda sekarang untuk menikmati kemudahan transaksi reksadana",
      "PROFILE_NOT_VERIFIED": "Satu langkah lagi untuk menikmati kemudahan transaksi reksadana, profil Anda sedang dalam proses verifikasi.",
      "MENU_PROFILE_SUBHEAD": "Silahkan mengisi Formulir Pembukaan Rekening Reksa Dana mengikuti penuh. Pastikan pengisian data Anda sesuai dengan data kepatuhan melekat",
      "PERSONAL_INFORMATION_TITLE": "Informasi Personal",
      "PERSONAL_INFORMATION_DESCRIPTION": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "SORT_BY_NAME": "Urutkan berdasarkan nama",
      "SORT_BY_PERFORMANCE": "Urutkan berdasarkan performa",
      "SORT_BY_NAV": "Urutkan berdasarkan NAV terakhir",
      "SORT_BY_TYPE": "Urutkan berdasarkan tipe",

      "FIRST_NAME_LABEL": "Nama depan",
      "MIDDLE_NAME_LABEL": "Nama tengah",
      "LAST_NAME_LABEL": "Nama belakang",
      "IDENTITY_LABEL": "Jenis Identitas",
      "IDENTITY_NUMBER_LABEL": "Nomor Identitas",
      "IDENTITY_EXPIRED_LABEL": "Masa berlaku identitas",
      "LIFETIME_LABEL": "Seumur hidup",
      "NPWP_INPUT_LABEL": "Nomor NPWP",
      "NATIONALITY_LABEL": "Kewarganegaraan",
      "BIRTH_PLACE_LABEL": "Tempat lahir",
      "BIRTH_DATE_LABEL": "Tanggal lahir",
      "BIRTH_COUNTRY_LABEL": "Negara tempat lahir",
      "GENDER_LABEL": "Jenis kelamin",
      "MARITAL_STATUS_LABEL": "Status pernikahan",
      "SPOUSE_NAME_LABEL": "Nama pasangan",
      "SPOUSE_BIRTH_PLACE_LABEL": "Tempat lahir pasangan",
      "SPOUSE_BIRTH_DATE_LABEL": "Tanggal lahir pasangan",
      "SPOUSE_MOBILE_PHONE_LABEL": "Nomor handphone pasangan",
      "MOTHER_MAIDEN_NAME_LABEL": "Nama gadis ibu kandung",
      "EDUCATION_LABEL": "Jenjang pendidikan",
      "RELIGION_LABEL": "Agama",
      "CORRESPONDENCE_ADDRESS_LABEL": "Alamat korespondensi",
      "CORRESPONDENCE_CITY_LABEL": "Nama kota korespondensi",
      "CORRESPONDENCE_CITY_OTHER_LABEL": "Nama kota korespondensi lainnya",
      "CORRESPONDENCE_POSTAL_CODE_LABEL": "Kodepos korespondensi",
      "CORRESPONDENCE_COUNTRY_LABEL": "Nama negara korespondensi",
      "SAME_AS_CORRESPONDENCE_LABEL": "Alamat tinggal sama dengan alamat korespondensi",
      "DOMICILE_ADDRESS_LABEL": "Alamat tempat tinggal",
      "DOMICILE_CITY_LABEL": "Nama kota tempat tinggal",
      "DOMICILE_CITY_OTHER_LABEL": "Nama kota tempat tinggal lainnya",
      "DOMICILE_POSTAL_CODE_LABEL": "Kodepos tempat tinggal",
      "DOMICILE_COUNTRY_LABEL": "Nama negara tempat tinggal",
      "EMAIL_LABEL": "Alamat email",
      "HANDPHONE_LABEL": "Nomor ponsel",
      "PHONE_LABEL": "Nomor telpon rumah",
      "FAX_LABEL": "Nomor fax",
      "ASSET_OWNERSHIP_LABEL": "Kepimilikan asset",
      "ASSET_OWNERSHIP_OTHER_LABEL": "Kepimilikan asset lainnya",
      "SID_LABEL": "SID",
      "STATEMENT_LABEL": "Pilihan statement",
      "KTP_LABEL": "Unggah KTP (gambar atau PDF)",
      "NPWP_LABEL": "Unggah NPWP (gambar atau PDF)",
      "DOESNT_HAVE_NPWP_LABEL": "Tidak memiliki NPWP",

      "JOB_INFORMATION_TITLE": "Informasi pekerjaan",
      "JOB_INFORMATION_DESCRIPTION": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      "OCCUPATION_LABEL": "Pekerjaan",
      "SPOUSE_OCCUPATION_LABEL": "Pekerjaan pasangan",
      "PARENT_OCCUPATION_LABEL": "Pekerjaan orang tua",
      "SPOUSE_NATURE_OF_BUSSINES_LABEL": "Jenis usaha pasangan",
      "PARENT_NATURE_OF_BUSSINES_LABEL": "Jenis usaha orang tua",
      "SPOUSE_NATURE_OF_BUSSINES_OTHER_LABEL": "Jenis usaha pasangan lainnya",
      "PARENT_NATURE_OF_BUSSINES_OTHER_LABEL": "Jenis usaha orang tua lainnya",
      "SPOUSE_ID_CARD_LABEL": "Nomor KTP Pasangan",
      "PARENT_ID_CARD_LABEL": "Nomor KTP Orang Tua",
      "SPOUSE_NATIONALITY_LABEL": "Kebangsaan pasangan",
      "PARENT_NATIONALITY_LABEL": "Kebangsaan orang tua",
      "OCCUPATION_OTHER_LABEL": "Pekerjaan lainnya",
      "OCCUPATION_NATURE_OF_BUSSINES_LABEL": "Jenis usaha",
      "OCCUPATION_NATURE_OF_BUSSINES_OTHER_LABEL": "Jenis usaha lainnya",
      "INCOME_LABEL": "Pendapatan",
      "SPOUSE_INCOME_LABEL": "Pendapatan pasangan",
      "PARENT_INCOME_LABEL": "Pendapatan orang tua",
      "SOURCE_OF_INCOME_LABEL": "Sumber pendapatan",
      "SOURCE_OF_INCOME_OTHER_LABEL": "Sumber penghasilan lainnya",

      "BANK_INFORMATION_TITLE": "Informasi bank",
      "BANK_INFORMATION_DESCRIPTION": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet.",
      "BANK_NAME_LABEL": "Nama bank",
      "BANK_BRANCH_NAME_LABEL": "Nama cabang bank",
      "BANK_ACCOUNT_NUMBER_LABEL": "Nomor rekening bank",
      "BANK_ACCOUNT_NAME_LABEL": "Nama rekening bank",
      "BANK_ADDRESS_LABEL": "Alamat bank",
      "CURRENCY_LABEL": "Mata uang",

      "INVESTMENT_PURPOSE_TITLE": "Tujuan Investasi",
      "INVESTMENT_PURPOSE_DESCRIPTION": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet.",
      "INVESTMENT_OBJECTIVE_LABEL": "Tujuan investasi",
      "INVESTMENT_OBJECTIVE_OTHER_LABEL": "Tujuan investasi lainnya",

      "RISK_PROFILE_TITLE": "Profil Resiko",
      "RISK_PROFILE_DESCRIPTION": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet.",
      "RISK_1_LABEL": "Pilih horizon/jangka waktu investasi anda",
      "RISK_2_LABEL": "Berapakah usia anda saat ini",
      "RISK_3_LABEL": "Hasil investasi manakah yang anda inginkan",
      "RISK_4_LABEL": "Tingkat resiko yang sanggup ditanggung dalam investasi",
      "RISK_5_LABEL": "Berapa besar alokasi investasi dalam reksa dana dari total aset yang dimiliki",
      "RISK_6_LABEL": "Tujuan pemanfaatan hasil investasi anda di reksa dana",
      "RISK_7_LABEL": "Sejauh mana pengetahuan anda mengenai reksa dana",
      "RISK_8_LABEL": "Bagaimana pendapat anda mengenai resiko penurunan (kerugian) nilai investasi anda",
      "YOUR_RISK_PROFILE_LABEL": "Profil Resiko Anda",

      "CUSTOMER_STATEMENT_TITLE": "Pernyataan Nasabah",
      "CUSTOMER_STATEMENT_DESCRIPTION": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet.",
      "TNC_CUST_STATMNT": "<div class=\"tnc tnc-profile\"><ol><li>Bahwa semua informasi yang saya berikan diatas adalah benar, lengkap, akurat, jujur, jelas dan tidak menyesatkan. Saya akan memberitahu [PTapp] apabila ada perubahan terhadap informasi tersebut diatas</li><li>Saya menegaskan bahwa saya telah menerima Prospektus terkini sehubungan Reksa Dana dan memahami isinya, serta pengisian Formulir ini berdasarkan pengertian tersebut.</li><li>Saya menegaskan bahwa saya telah membaca, memahami dan menerima Syarat dan Ketentuan terlampir (yang sebagaimana dapat diubah, dimodifikasi dan ditambahkan dari waktu ke waktu sesuai dengan hukum yang berlaku di Indonesia) dan terikat padanya.</li><li>Saya menegaskan bahwa seluruh informasi yang saya berikan dalam Formulir ini akan selalu benar dan sah dan saya berjanji akan segera memberitahukan [PTapp] jika terjadi perubahan terhadapnya.</li><li>Saya mengerti bahwa semua data yang disebutkan dalam Formulir KYC ini dapat digunakan sebagai pengkinian data nasabah. Saya tunduk pada Undang-Undang dan Peraturan yang berlaku termasuk tetapi tidak terbatas pada Undang-Undang No.8 Tahun 2010 mengenai Pencegahan dan Pemberantasan Tindak Pidana Pencucian Uang, Undang-Undang No.9 Tahun 2013 mengenai Pencegahan dan Pemberantasan Tindak Pidana Pendanaan Terorisme dan Peraturan OJK No.22 Tahun 2014 mengenai Prinsip Mengenal Nasabah Oleh Penyedia Jasa Keuangan Di Sektor Pasar Modal.</li><li>Saya mengizinkan [PTapp] untuk merekam komunikasi lisan yang kami berikan termasuk saat tatap muka maupun melalui telepon maupun sarana komunikasi lainnya, termasuk melalui short message service (SMS), Blackberry messenger (BBM) dan media elektronik lainnya. Hasil rekaman tersebut dapat digunakan sebagai pembuktian pelaksanaan KYC, transaksi, dan hal lainnya terkait kepemilikan Reksa Dana [app], termasuk apabila di kemudian hari terjadi perselisihan antara kami dan PT [app] Asset Management.</li></ol></div>",
      "TERMS_COND_LABEL": "Saya setuju dengan pernyataan Nasabah tentang Pembukaan Rekening [app]",

      "REVIEW_TITLE": "Tinjau Ulang",
      "REVIEW_DESCRIPTION": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet.",

      "SUCCESS_FORM_SUBMITED": "Profile Anda telah berhasil disimpan, kami akan mereview profil Anda",

      "PRODUCT_DETAIL_LABEL": "Informasi Produk",
      "PRODUCT_PERFORMANCE_LABEL": "Informasi Performa Produk",
      "PRODUCT_NEWS_AND_PROMO_LABEL": "Berita dan Promo",

      "FUND_NAME_LABEL": "Nama produk",
      "TYPE_LABEL": "Tipe produk",
      "NAV_AS_OF_LABEL": "NAB per",
      "BALANCE_LABEL": "Saldo dalam unit",

      "BUY_LABEL": "BELI",
      "SELL_LABEL": "JUAL",
      "SWITCH_LABEL": "SWITCH",

      "SEND_PAYMENT_LABEL": "Transaksi Anda sedang di proses. Silahkan melakukan pembayaran <strong>sebelum pukul 13:00</strong> hari ini ke rekening berikut: ",
      "SEND_PAYMENT2_LABEL": "<strong>Jika Anda tidak melakukan pembayaran dalam jangka waktu 3 hari, maka transaksi Anda akan di hapus dari sistem.</strong>",
      "SEND_PAYMENT3_LABEL": "<strong>Dana akan Anda terima maksimum 7 hari kerja setelah transaksi ini disetujui.</strong>",
      "SEND_PAYMENT4_LABEL": "<strong>Setelah diverifikasi, pengalihan produk Anda akan segera diproses.</strong>",

      "RISK_NOT_MATCH_LABEL": "Risk profile anda tidak sesuai dengan produk ini",
      "ARE_YOU_SURE_LABEL": "Apakah Anda yakin untuk mengubah KYC?",
      "NO_UNIT_LABEL": "Anda tidak memiliki unit untuk Reksa Dana ini",

      "MINIMUM_LABEL": "Minimal",
      "AMOUNT_LABEL": "Amount",
      "CODE_LABEL": "Kode Verifikasi",
      "SEND_LABEL": "Kirim",

      "CODE_SUCCESSFULLY_SENT_LABEL": "Kode verifikasi berhasil dikirim, silahkan periksa email / hanphone Anda.",
      "TOOMUCH_CODE_REQUEST": "Maaf, kami tidak memungkinkan untuk mengirim ulang kode keamanan Anda lebih dari 3 kali. Harap hubungi contact support kami",

      "AGREEMENT_TRANSACTION": "Saya menyetujui untuk melakukan transaksi dengan [app] dan menyetujui ",
      "TAC": "Syarat dan Ketentuan",
      "TRANSACTION_SUCCESS_LABEL": "Transaksi Anda berhasil di proses",

      "YOU_HAVE_LABEL": "Unit product yang Anda miliki adalah",
      "MIN_SELL_LABEL": "Minimal jual",
      "MIN_BALANCE_LABEL": "Saldo minimal setelah transaksi",
      "YOUR_REMAINING_BALANCE_LABEL": "Sisa saldo Anda",

      "SELECT_BANK_LABEL": "Pilih bank tujuan Anda",
      "TERMS_CONDITION_LABEL": "Syarat dan Ketentuan",
      "SELECT_PRODUCT_SWITCH_LABEL": "Pilih produk target Anda",

      "AVAILABLE_BALANCE_LABEL": "Dana Tersedia",
      "AVAILABLE_UNIT_LABEL": "Unit Tersedia",

      "NOT_RECOMENDED_LABEL": "[PTapp] (termasuk anak perusahaan, asosiasi, dan afiliasinya) ([app]) tidak memberikan suatu penawaran, saran, atau rekomendasi untuk berinvestasi di Reksa Dana yang telah saya/kami beli. Dalam hal ini, saya/kami bertindak sendiri dalam menganalisa dan memilih Reksa Dana tersebut dan keputusan berinvestasi dilakukan tidak sesuai saran atau rekomendasi dari [app].",

      "LAST_NAV_LABEL": "NAB Terakhir",
      "MY_PORTOFOLIO_LABEL": "Portofolio Anda",
      "OTHER_PRODUCT_LABEL": "Produk lainnya",

      "TRANSACTION_LIST_LABEL": "Data Transaksi Anda",
      "FIRST_LABEL": "Awal",
      "NEXT_LABEL": "Berikut",
      "PREVIOUS_LABEL": "Sebelum",
      "LAST_LABEL": "Akhir",

      "PENDING_LABEL": "Tertunda",
      "WAIT_FOR_VERIFICATION_LABEL": "Menunggu verifikasi",
      "COMPLETE_LABEL": "Berhasil",
      "EXPIRED_LABEL": "Kadaluarsa",
      "TOTAL_BUY_LABEL": "Total beli",
      "TOTAL_SELL_LABEL": "Total jual",
      "TRANSACTION_DATE_LABEL": "Tanggal transaksi",
      "FEE_LABEL": "Biaya transaksi",

      "PDF_DOWNLOAD_LABEL": "Unduh Profil dalam bentuk PDF",
      "EDIT_PROFILE_LABEL": "Ubah profil",

      "THERE_IS_NO_DATA_LABEL": "Tidak ada data untuk ditampilkan",

      "PENDING_TRANSACTION_NOTIFICATION_LABEL": "Anda memiliki beberapa transaksi yang membutuhkan konfirmasi. Segera konfirmasi transaksi Anda agar dapat segera kami proses.",

      "TRANSACTION_DETAIL": "Detail transaksi",
      "TRANSACTION_TYPE_LABEL": "Tipe Transaksi",


      "CONFIRMATION_DATA_LABEL": "Data konfirmasi pembayaran",
      "BANK_FROM_LABEL": "Dikirim dari",
      "BANK_DESTINATION_LABEL": "Bank tujuan",
      "PAYMENT_PROOF_LABEL": "Bukti pembayaran",
      "PAYMENT_DATE_LABEL": "Tanggal pembayaran",

      "CONFIRM_TRANSACTION_LABEL": "Konfirmasi pembayaran",

      "REPEAT_LABEL": "Ulangi",
      "CONTINUE_LABEL": "Lanjutkan",
      "CLOSE_LABEL": "Tutup",
      "ATTENTION_LABEL": "Perhatian",
      "CONFIRM_LESS_THAN_LABEL": "Transaksi Anda kurang dari jumlah yang sudah Anda masukkan. Silakan hubungi Client Service atau ulang transaksi Anda.",
      "CONFIRM_MORE_THAN_LABEL": "Transaksi Anda lebih dari jumlah yang sudah Anda masukkan. Apakah Anda ingin melanjutkan atau mengulang transaksi?",
      "CONFIRM_SUCCESS_LABEL": "Setelah diverifikasi, pembelian produk Anda akan segera diproses.",
      "CONFIRM_SUCCESS_WITH_WARNING": "Konfirmasi Anda sudah lewat pukul 13.00 WIB. Setelah diverifikasi, pembelian produk Anda akan segera diproses pada hari bursa berikutnya.",


      "OLD_PASSWORD_LABEL": "Kata sandi lama",
      "NEW_PASSWORD_LABEL": "Kata sandi baru",
      "NEW_PASSWORD_CONFIRMATION_LABEL": "Konfirmasi kata sandi baru",

      "CHANGE_PASSWORD_SUCCESS_LABEL": "Kata sandi Anda berhasil diubah",
      "CHANGE_PASSWORD_FAILED_LABEL": "Kata sandi lama Anda tidak benar, silahkan coba kembali",

      "PLEASE_SIGN_HERE_LABEL": "Mohon bubuhkan tanda tangan disini *",

      "GREETING_WELCOME": "Masuk",
      "GREETING_MORNING": "",
      "GREETING_AFTERNOON": "",
      "GREETING_EVENING": "",
      "ENTER_YOUR_DETAIL": "untuk melanjutkan ke <strong>PayOr</strong>",
      "YOUR_EMAIL_LABEL": "Email Anda",
      "YOUR_PASSWORD_LABEL": "Katasandi Anda",
      "OUR_PRODUCT_LABEL": "Produk Kami",
      "GOOD_DAY_LABEL": "Selamat datang kembali",

      "CONSERVATIVE_LABEL": "Konservatif",
      "AGGRESSIVE_LABEL": "Agresif",
      "BALANCE_LABEL": "Seimbang",
      "SIGNIN_LABEL": "Masuk",
      "REGISTER_LABEL": "Daftar"
    }
  }
};
